name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - name: チェックアウト
      uses: actions/checkout@v3
    - name: JDK 17をセットアップ
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: プラグインをビルド
      run: mvn -B package --file pom.xml
    - name: original-*.jarを削除
      run: rm target/original-*.jar
    - name: リリース
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        files: 'target/*.jar'
